### ISSUE TITLE
Build anti-cheat

### ISSUE THREAD

**Issue by Cylae** [elysium-project/core#6]
Hello,

During the compilation we can see an anti-cheat option, how to enable it ?

**Comment by brotalnia** [comment]
They forgot to upload the module folder required for the anti-cheat. It compiles fine if you take it from the leaked source and paste it here, but they also didn't include the database tables used for warden and you will have to create them manually based on the queries it tries to perform.

**Comment by Kittnz** [comment]
I don't they wanted to anti cheat opensource.

**Comment by shenna-elysium** [comment]
We didn't publish anti cheat for a reason. Its development will continue in private repository as it should be.
